services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspaces/bikerflow:cached
    working_dir: /workspaces/bikerflow
    tmpfs:
      - /workspaces/bikerflow/storage/framework/cache
      - /workspaces/bikerflow/storage/framework/sessions
    networks:
      - biker-network

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: bikerflow
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../.snapshots:/snapshots
    networks:
      - biker-network

networks:
  biker-network:
    driver: bridge